name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MinGW
        run: choco install mingw -y

      - name: Compile C++ to EXE
        run: g++ main.cpp -o shape.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: shape-exe
          path: shape.exe
